[window]

opacity = 0.95
blur = true
dimensions = {columns = 100, lines=40}

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "ArrowUp", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "ArrowDown", mods = "Control|Shift", action = "DecreaseFontSize" },
]

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font Bold"
italic.family = "JetBrainsMono Nerd Font Italic"
bold_italic.family = "JetBrainsMono Nerd Font Bold Italic"
size = 12
